apiVersion: apps/v1
kind: Deployment
metadata:
  name: gds-deployment
  labels:
    app: gds-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gds-app
  template:
    metadata:
      labels:
        app: gds-app
    spec:
      containers:
      - name: gds-container
        image: sguri003/gds-app:v3
        ports:
        - containerPort: 8000