apiVersion: apps/v1
kind: Deployment
metadata:
  name: gds_deployment
  labels:
    app: gds_app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gds_app
  template:
    metadata:
      labels:
        app: gds_app
    spec:
      containers:
        - name: gds:v5
          image: sguri003/gds:v5
          ports:
            - containerPort: 8080