apiVersion: v1
kind: Service
metadata:
  name: gds-service
  annotations:
    # Provisions an AWS Network Load Balancer (NLB) instead of a legacy Classic Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    # Determines how traffic paths to pods. "nlb-ip" routes traffic directly to the pod IP addresses
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
    # Forces the load balancer to be internet-facing instead of internal
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: gds-app
  ports:
    - name: http
      protocol: TCP
      port: 80          # The external port exposed by the load balancer
      targetPort: 8000    # The containerPort specified in your deployment